"""
S6E4 V31 - XGBoost on Formula + Groupby Target Statistics (GPU)
================================================================================
Diversity Tier: Tier 1 — Formula Features × Per-Fold Groupby Stats
Lock Broken: Feature Lock (47 features vs ~340) + Encoding Lock (per-fold groupby vs TE)

Model: XGBoost with BA early stopping
Data:  9 binary Deotte formula features + 38 groupby target statistics
       ALL computed from competition train/test data ONLY
       NO external datasets, NO Target Encoding, NO digit features, NO noise features

Reference:
- Chris Deotte: https://www.kaggle.com/code/cdeotte/original-data-exact-formula
  -> Data generated by logistic regression on 9 binary features
  -> Only 6 raw features carry signal, remaining 13 are noise
- include4eto: https://www.kaggle.com/code/include4eto/ps6e4-tab-transformer-claude-vibe-coding
  -> Groupby target statistics idea: mean(target) and std(target) per feature value
  -> Adapted: computed per-fold from competition train (not original dataset)

Key Design:
  38 groupby features computed PER-FOLD from training fold only (no leakage):
    For each of 19 columns, compute:
      STATS_{col}_mean = mean(target) grouped by column value
      STATS_{col}_std  = std(target)  grouped by column value
    Then left-merge onto train fold, val fold, and test.
    NaN fill: mean -> 0.5, std -> 0.

  Why per-fold? Computing globally from all train data would leak target info
  into validation (OOF) predictions. Per-fold ensures OOF integrity.

  Difference from V1's Target Encoding:
    V1: sklearn TargetEncoder(target_type='multiclass', cv=5, smooth='auto')
        -> Produces 3 columns per feature (one per class), uses smoothing
        -> Applied to 74+ columns (categoricals + digit features)
    V31: Simple groupby mean+std (2 columns per feature), no smoothing
        -> Applied to only 19 original columns
        -> Plus 9 formula binary features
        -> Total: 47 features (vs V1's ~340)

Features (47 total):
  9 Binary Formula Features (Deotte's generative formula):
    1. soil_lt_25      = Soil_Moisture < 25
    2. temp_gt_30      = Temperature_C > 30
    3. rain_lt_300     = Rainfall_mm < 300
    4. wind_gt_10      = Wind_Speed_kmh > 10
    5. stage_flowering = (Crop_Growth_Stage == 'Flowering')
    6. stage_harvest   = (Crop_Growth_Stage == 'Harvest')
    7. stage_sowing    = (Crop_Growth_Stage == 'Sowing')
    8. stage_vegetative= (Crop_Growth_Stage == 'Vegetative')
    9. mulching_yes    = (Mulching_Used == 'Yes')

  38 Groupby Target Statistics (per-fold from competition train):
    For 8 categorical columns:
      STATS_Soil_Type_{mean,std}, STATS_Crop_Type_{mean,std},
      STATS_Crop_Growth_Stage_{mean,std}, STATS_Season_{mean,std},
      STATS_Irrigation_Type_{mean,std}, STATS_Water_Source_{mean,std},
      STATS_Mulching_Used_{mean,std}, STATS_Region_{mean,std}
    For 11 numerical columns:
      STATS_Soil_pH_{mean,std}, STATS_Soil_Moisture_{mean,std},
      STATS_Organic_Carbon_{mean,std}, STATS_Electrical_Conductivity_{mean,std},
      STATS_Temperature_C_{mean,std}, STATS_Humidity_{mean,std},
      STATS_Rainfall_mm_{mean,std}, STATS_Sunlight_Hours_{mean,std},
      STATS_Wind_Speed_kmh_{mean,std}, STATS_Field_Area_hectare_{mean,std},
      STATS_Previous_Irrigation_mm_{mean,std}

Why diversity:
  - Feature Lock broken: 47 features vs V1's ~340 (86% fewer)
  - Encoding Lock broken: per-fold groupby mean+std (no smoothing, no cv=5 TE)
    vs V1's sklearn TargetEncoder(smooth='auto', cv=5)
  - No digit features, no frequency encoding, no noise columns
  - Categorical groupby stats capture category->target mapping directly
  - Numerical groupby stats capture how target varies with raw values

Expected: BA ~0.968-0.978 | Disagreement from V1 ~10-15%
Est. Time: ~20 min (47 features, XGB GPU, per-fold groupby overhead)

Pipeline: Load data -> Create 9 binary features -> Per-fold:
          Compute groupby stats (38) -> XGB -> Raw OOF -> Class weight opt -> Final

No ensembling, no blending, no multi-seed (Rule 6).
No external datasets required.
"""

import warnings
import gc
import time
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
import xgboost as xgb

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 100)

class CFG:
    VERSION_NAME = "v31"
    EXP_ID = "S6E4_V31_XGB_Formula_GroupbyStats"
    DEVICE = "GPU"
    TRAIN_PATH = "/kaggle/input/datasets/blamerx/oof-and-submission/S6E4/Dataset/train.csv"
    TEST_PATH = "/kaggle/input/datasets/blamerx/oof-and-submission/S6E4/Dataset/test.csv"
    TARGET = 'Irrigation_Need'
    NUM_CLASSES = 3
    N_FOLDS = 10
    RANDOM_SEED = 2026
    MAX_ROUNDS = 2000
    ES_ROUNDS = 150

# All 19 original columns
CATS = ['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season',
        'Irrigation_Type', 'Water_Source', 'Mulching_Used', 'Region']
NUMS = ['Soil_pH', 'Soil_Moisture', 'Organic_Carbon', 'Electrical_Conductivity',
        'Temperature_C', 'Humidity', 'Rainfall_mm', 'Sunlight_Hours',
        'Wind_Speed_kmh', 'Field_Area_hectare', 'Previous_Irrigation_mm']
ALL_COLS = CATS + NUMS  # 19 columns

BINARY_FEATURES = [
    'soil_lt_25', 'temp_gt_30', 'rain_lt_300', 'wind_gt_10',
    'stage_flowering', 'stage_harvest', 'stage_sowing',
    'stage_vegetative', 'mulching_yes',
]

XGB_PARAMS = {
    'objective': 'multi:softprob',
    'num_class': 3,
    'tree_method': 'hist',
    'device': 'cuda',
    'random_state': CFG.RANDOM_SEED,
    'max_depth': 4,
    'learning_rate': 0.05,
    'subsample': 0.7,
    'colsample_bytree': 0.6,
    'reg_alpha': 10,
    'reg_lambda': 10,
    'min_child_weight': 12,
    'max_bin': 512,
}

def accuracy_score(y_true, y_pred):
    if len(y_pred.shape) == 2:
        y_pred = np.argmax(y_pred, axis=1)
    C = 3
    acc = 0.0
    for i in range(C):
        acc += np.sum((y_true == i) & (y_pred == i)) / np.sum(y_true == i) / C
    return acc

def create_deotte_binary_features(df):
    """Create 9 binary features from Chris Deotte's reverse-engineered formula."""
    df = df.copy()
    df['soil_lt_25'] = (df['Soil_Moisture'] < 25).astype(np.int8)
    df['temp_gt_30'] = (df['Temperature_C'] > 30).astype(np.int8)
    df['rain_lt_300'] = (df['Rainfall_mm'] < 300).astype(np.int8)
    df['wind_gt_10'] = (df['Wind_Speed_kmh'] > 10).astype(np.int8)
    df['stage_flowering'] = (df['Crop_Growth_Stage'] == 'Flowering').astype(np.int8)
    df['stage_harvest'] = (df['Crop_Growth_Stage'] == 'Harvest').astype(np.int8)
    df['stage_sowing'] = (df['Crop_Growth_Stage'] == 'Sowing').astype(np.int8)
    df['stage_vegetative'] = (df['Crop_Growth_Stage'] == 'Vegetative').astype(np.int8)
    df['mulching_yes'] = (df['Mulching_Used'] == 'Yes').astype(np.int8)
    return df

def compute_fold_groupby_stats(train_fold, y_train, all_cols):
    """
    Compute per-fold groupby target statistics.
    For each of 19 columns, compute mean(target) and std(target) grouped by value.
    Returns: stats_lookup dict for merging, list of stats column names.
    """
    stats_lookup = {}
    stats_cols = []

    for col in all_cols:
        col_values = train_fold[col].values
        stats = pd.DataFrame({'_val': col_values, '_target': y_train})
        grouped = stats.groupby('_val')['_target'].agg(['mean', 'std']).reset_index()
        grouped.columns = ['_val', f'STATS_{col}_mean', f'STATS_{col}_std']

        # Store as dict for fast lookup
        mean_map = dict(zip(grouped['_val'], grouped[f'STATS_{col}_mean']))
        std_map = dict(zip(grouped['_val'], grouped[f'STATS_{col}_std']))
        stats_lookup[col] = (mean_map, std_map)
        stats_cols.extend([f'STATS_{col}_mean', f'STATS_{col}_std'])

    return stats_lookup, stats_cols

def apply_groupby_stats(df, stats_lookup, all_cols, stats_cols):
    """Apply pre-computed groupby stats to a dataframe via lookup."""
    for col in all_cols:
        mean_map, std_map = stats_lookup[col]
        df[f'STATS_{col}_mean'] = df[col].map(mean_map).fillna(0.5).astype(np.float32)
        df[f'STATS_{col}_std'] = df[col].map(std_map).fillna(0.0).astype(np.float32)
    return df

def ba_eval_metric(preds, dtrain):
    """Balanced Accuracy eval metric for XGBoost native API early stopping."""
    labels = dtrain.get_label().astype(int)
    n = len(labels)
    C = CFG.NUM_CLASSES
    if preds.ndim == 1:
        preds = preds.reshape(n, C)
    pred_labels = np.argmax(preds, axis=1)
    recalls = []
    for c in range(C):
        mask = labels == c
        if mask.sum() > 0:
            recalls.append((pred_labels[mask] == c).mean())
    return 'BA', float(np.mean(recalls))

def optimize_class_weights(oof_probs, y_true, n_trials=200):
    best_score = accuracy_score(y_true, oof_probs)
    best_weights = [1.0, 1.0, 1.0]
    for trial in range(n_trials):
        cw1 = np.random.uniform(0.5, 3.0)
        cw2 = np.random.uniform(0.5, 3.0)
        cw3 = np.random.uniform(0.5, 3.0)
        weights = np.array([cw1, cw2, cw3])
        adjusted_probs = oof_probs * weights
        preds = np.argmax(adjusted_probs, axis=1)
        score = accuracy_score(y_true, preds)
        if score > best_score:
            best_score = score
            best_weights = [cw1, cw2, cw3]
    print(f"   Optimized BA: {best_score:.5f}")
    print(f"   Best Weights: [{best_weights[0]:.4f}, {best_weights[1]:.4f}, {best_weights[2]:.4f}]")
    return best_weights

if __name__ == "__main__":
    t0_all = time.time()
    print("="*80)
    print(f"Starting {CFG.EXP_ID}")
    print(f"Device: {CFG.DEVICE}")
    print(f"Folds: {CFG.N_FOLDS}")
    print("="*80)

    # =========================================================================
    # [1/5] LOAD DATA
    # =========================================================================
    print("\n[1/5] Loading data...")
    train = pd.read_csv(CFG.TRAIN_PATH)
    test = pd.read_csv(CFG.TEST_PATH)
    train = train.drop(columns=['id'])
    test_id = pd.read_csv(CFG.TEST_PATH)['id']
    test = test.drop(columns=['id'])
    print(f"   Train shape: {train.shape}")
    print(f"   Test shape: {test.shape}")

    target2idx = {'Low': 0, 'Medium': 1, 'High': 2}
    idx2target = {0: 'Low', 1: 'Medium', 2: 'High'}
    train[CFG.TARGET] = train[CFG.TARGET].map(target2idx)

    print("\n   Class Distribution:")
    class_counts = train[CFG.TARGET].value_counts().sort_index()
    for cls, count in class_counts.items():
        print(f"     Class {cls}: {count:,} ({100*count/len(train):.1f}%)")

    # =========================================================================
    # [2/5] CREATE BINARY FORMULA FEATURES
    # =========================================================================
    print("\n[2/5] Creating 9 Deotte binary formula features...")
    train = create_deotte_binary_features(train)
    test = create_deotte_binary_features(test)
    print(f"   Binary features: {len(BINARY_FEATURES)}")

    # =========================================================================
    # [3/5] TRAINING (per-fold groupby stats)
    # =========================================================================
    unique, counts = np.unique(train[CFG.TARGET].values, return_counts=True)
    count_dict = dict(zip(unique, counts))
    avg_count = len(train) / len(unique)
    weights_dict = {cls: avg_count / cnt for cls, cnt in count_dict.items()}
    sample_weights = np.array([weights_dict[y] for y in train[CFG.TARGET]])

    # Pre-compute stats column names (same for every fold)
    _, stats_cols = compute_fold_groupby_stats(
        train.iloc[:1000], train[CFG.TARGET].iloc[:1000].values, ALL_COLS
    )
    FEATURES = BINARY_FEATURES + stats_cols
    print(f"   Groupby stats features: {len(stats_cols)} (per-fold from train)")
    print(f"   Total features: {len(FEATURES)}")

    print(f"\n[3/5] Training XGBoost ({CFG.N_FOLDS}-Fold CV)...")
    print(f"   Early stopping on: BA (maximize)")
    print(f"   Max rounds: {CFG.MAX_ROUNDS} | ES rounds: {CFG.ES_ROUNDS}")

    X_base = train[BINARY_FEATURES + ALL_COLS].copy()
    y = train[CFG.TARGET]
    test_base = test[BINARY_FEATURES + ALL_COLS].copy()
    oof_probs = np.zeros((len(y), CFG.NUM_CLASSES))
    test_probs = np.zeros((len(test_base), CFG.NUM_CLASSES))
    kf = StratifiedKFold(n_splits=CFG.N_FOLDS, shuffle=True, random_state=42)
    fold_scores = []
    t0 = time.time()

    for fold, (train_idx, val_idx) in enumerate(kf.split(X_base, y)):
        fold_start = time.time()
        print(f"\n   Fold {fold+1}/{CFG.N_FOLDS}: Computing stats + Training...", end=" ", flush=True)

        # Split base data (binaries + raw columns for groupby)
        X_train_base = X_base.iloc[train_idx].copy()
        X_val_base = X_base.iloc[val_idx].copy()
        X_test_base = test_base.copy()
        y_tr = y.iloc[train_idx].values.astype(np.float32)
        y_val = y.iloc[val_idx].values.astype(np.float32)
        train_weights = sample_weights[train_idx]

        # Compute groupby stats from TRAIN FOLD ONLY (no leakage)
        stats_lookup, _ = compute_fold_groupby_stats(X_train_base, y_tr, ALL_COLS)

        # Apply stats to train, val, and test
        X_train_base = apply_groupby_stats(X_train_base, stats_lookup, ALL_COLS, stats_cols)
        X_val_base = apply_groupby_stats(X_val_base, stats_lookup, ALL_COLS, stats_cols)
        X_test_base = apply_groupby_stats(X_test_base, stats_lookup, ALL_COLS, stats_cols)

        # Extract feature matrix
        X_train = X_train_base[FEATURES].values.astype(np.float32)
        X_val = X_val_base[FEATURES].values.astype(np.float32)
        X_test_np = X_test_base[FEATURES].values.astype(np.float32)

        dtrain = xgb.DMatrix(X_train, label=y_tr, weight=train_weights)
        dval = xgb.DMatrix(X_val, label=y_val)
        dtest = xgb.DMatrix(X_test_np)

        bst = xgb.train(
            XGB_PARAMS, dtrain, num_boost_round=CFG.MAX_ROUNDS,
            evals=[(dval, 'val')],
            custom_metric=ba_eval_metric,
            early_stopping_rounds=CFG.ES_ROUNDS,
            maximize=True, verbose_eval=False,
        )
        best_iter = bst.best_iteration + 1

        val_probs = bst.predict(dval).reshape(-1, CFG.NUM_CLASSES)
        oof_probs[val_idx] = val_probs
        test_probs += bst.predict(dtest).reshape(-1, CFG.NUM_CLASSES) / CFG.N_FOLDS

        fold_acc = accuracy_score(y_val, val_probs)
        fold_scores.append(fold_acc)

        del dtrain, dval, dtest, bst, stats_lookup
        gc.collect()

        elapsed = (time.time() - t0) / 60
        print(f"BA: {fold_acc:.5f} | Iter: {best_iter} | Time: {time.time()-fold_start:.0f}s | Total: {elapsed:.1f}min")

    oof_cv = accuracy_score(y.values, oof_probs)
    print(f"\n   Raw OOF BA: {oof_cv:.5f}")

    # =========================================================================
    # [4/5] CLASS WEIGHT OPTIMIZATION
    # =========================================================================
    print(f"\n[4/5] Optimizing class weights...")
    optimal_weights = optimize_class_weights(oof_probs, y.values, n_trials=200)
    weights = np.array(optimal_weights)
    oof_probs_opt = oof_probs * weights
    test_probs_opt = test_probs * weights
    opt_cv = accuracy_score(y.values, np.argmax(oof_probs_opt, axis=1))
    print(f"   Optimized OOF BA: {opt_cv:.5f}")

    # =========================================================================
    # [5/5] SAVE OUTPUTS
    # =========================================================================
    print(f"\n[5/5] Saving outputs...")
    np.save(f"oof_probs_{CFG.VERSION_NAME}.npy", oof_probs_opt)
    np.save(f"test_probs_{CFG.VERSION_NAME}.npy", test_probs_opt)
    print(f"   [SAVED] test_probs_{CFG.VERSION_NAME}.npy (shape: {test_probs_opt.shape})")
    print(f"   oof_probs_{CFG.VERSION_NAME}.npy")
    sub_df = pd.DataFrame({
        'id': test_id,
        CFG.TARGET: [idx2target[p] for p in np.argmax(test_probs_opt, axis=1)]
    })
    sub_df.to_csv(f"sub_{CFG.VERSION_NAME}.csv", index=False)
    print(f"   sub_{CFG.VERSION_NAME}.csv")

    print(f"\n{'='*80}")
    print(f"V31 RESULTS — XGBoost Formula + Groupby Stats ({CFG.DEVICE})")
    print(f"{'='*80}")
    print(f"Raw OOF BA: {oof_cv:.5f}")
    print(f"Optimized OOF BA: {opt_cv:.5f}")
    print(f"Weights: [{optimal_weights[0]:.4f}, {optimal_weights[1]:.4f}, {optimal_weights[2]:.4f}]")
    print(f"Fold scores: {[f'{s:.5f}' for s in fold_scores]}")
    print(f"\nTotal time: {(time.time() - t0_all) / 60:.1f} min")
    print("="*80)
