"""
S6E4 V30 - LightGBM on Signal-Only 6 Raw Features (CPU)
================================================================================
Diversity Tier: Tier 1 — Formula Features × Different Algorithm
Lock Broken: Feature Lock (6 raw features vs ~340) + Encoding Lock (NO TE, LGBM native cats)

Model: LightGBM (best CPU model for speed-quality tradeoff)
Data:  6 raw signal features only — the exact features that generate the data
       NO Target Encoding, NO digit features, NO frequency encoding, NO noise features
       Categoricals handled by LGBM natively (Fisher optimal splits)

Reference:
- Chris Deotte: https://www.kaggle.com/competitions/playground-series-s6e4/discussion/687460
  -> Data generated by formula using only 6 features:
     Soil_Moisture, Temperature_C, Rainfall_mm, Wind_Speed_kmh (numerical)
     Crop_Growth_Stage, Mulching_Used (categorical)
  -> All other 13 features are NOISE
- @aerdem4: https://www.kaggle.com/competitions/playground-series-s6e4/discussion/687104
  -> Confirmed effective number of features is 6

Key difference from V26-V29: V30 gives the model RAW continuous values.
V26-V29 use pre-defined thresholds (binary or logit). V30 lets LightGBM find
its own optimal splits on the continuous signal features. This means:
  - V30 and V26-V29 will DISAGREE with each other (different representations)
  - V30 has more flexibility near threshold boundaries
  - V30 uses ZERO TE (LGBM native categorical handling vs 74+ TE cols in V1)

6 Features:
  1. Soil_Moisture (continuous)
  2. Temperature_C (continuous)
  3. Rainfall_mm (continuous)
  4. Wind_Speed_kmh (continuous)
  5. Crop_Growth_Stage (categorical → LGBM native)
  6. Mulching_Used (categorical → LGBM native)

Expected: BA ~0.965-0.978 | Disagreement from V1 ~10-15% | From V26 ~5-10%
Est. Time: ~30 min (CPU, 6 features, LGBM)

Pipeline: Load data -> Select 6 signal features -> LabelEncode categoricals ->
          LGBM CPU (native cat handling) -> Raw OOF -> Class weight optimization -> Final

No ensembling, no blending, no multi-seed (Rule 6).
"""

import warnings
import gc
import time
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
import lightgbm as lgb

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 100)

class CFG:
    VERSION_NAME = "v30"
    EXP_ID = "S6E4_V30_LGBM_Signal_Only"
    DEVICE = "GPU"
    TRAIN_PATH = "/kaggle/input/datasets/blamerx/oof-and-submission/S6E4/Dataset/train.csv"
    TEST_PATH = "/kaggle/input/datasets/blamerx/oof-and-submission/S6E4/Dataset/test.csv"
    TARGET = 'Irrigation_Need'
    NUM_CLASSES = 3
    N_FOLDS = 10
    RANDOM_SEED = 2026

# 6 signal features (Deotte's generative features)
NUM_FEATURES = ['Soil_Moisture', 'Temperature_C', 'Rainfall_mm', 'Wind_Speed_kmh']
CAT_FEATURES = ['Crop_Growth_Stage', 'Mulching_Used']

LGBM_PARAMS = {
    'objective': 'multiclass',
    'num_class': 3,
    'boosting_type': 'gbdt',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'max_depth': 6,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.7,
    'bagging_freq': 5,
    'reg_alpha': 5,
    'reg_lambda': 5,
    'min_child_samples': 20,
    'verbose': -1,
    'random_state': CFG.RANDOM_SEED,
    'device_type': 'gpu',
    'gpu_platform_id': 0,
    'gpu_device_id': 0,
}

def accuracy_score(y_true, y_pred):
    if len(y_pred.shape) == 2:
        y_pred = np.argmax(y_pred, axis=1)
    C = 3
    acc = 0.0
    for i in range(C):
        acc += np.sum((y_true == i) & (y_pred == i)) / np.sum(y_true == i) / C
    return acc

def optimize_class_weights(oof_probs, y_true, n_trials=200):
    best_score = accuracy_score(y_true, oof_probs)
    best_weights = [1.0, 1.0, 1.0]
    for trial in range(n_trials):
        cw1 = np.random.uniform(0.5, 3.0)
        cw2 = np.random.uniform(0.5, 3.0)
        cw3 = np.random.uniform(0.5, 3.0)
        weights = np.array([cw1, cw2, cw3])
        adjusted_probs = oof_probs * weights
        preds = np.argmax(adjusted_probs, axis=1)
        score = accuracy_score(y_true, preds)
        if score > best_score:
            best_score = score
            best_weights = [cw1, cw2, cw3]
    print(f"   Optimized BA: {best_score:.5f}")
    print(f"   Best Weights: [{best_weights[0]:.4f}, {best_weights[1]:.4f}, {best_weights[2]:.4f}]")
    return best_weights

if __name__ == "__main__":
    t0_all = time.time()
    print("="*80)
    print(f"Starting {CFG.EXP_ID}")
    print(f"Device: {CFG.DEVICE}")
    print(f"Folds: {CFG.N_FOLDS}")
    print("="*80)

    print("\n[1/5] Loading data...")
    train = pd.read_csv(CFG.TRAIN_PATH)
    test = pd.read_csv(CFG.TEST_PATH)
    train = train.drop(columns=['id'])
    test_id = pd.read_csv(CFG.TEST_PATH)['id']
    test = test.drop(columns=['id'])
    print(f"   Train shape: {train.shape}")
    print(f"   Test shape: {test.shape}")

    target2idx = {'Low': 0, 'Medium': 1, 'High': 2}
    idx2target = {0: 'Low', 1: 'Medium', 2: 'High'}
    train[CFG.TARGET] = train[CFG.TARGET].map(target2idx)

    print("\n   Class Distribution:")
    class_counts = train[CFG.TARGET].value_counts().sort_index()
    for cls, count in class_counts.items():
        print(f"     Class {cls}: {count:,} ({100*count/len(train):.1f}%)")

    print("\n[2/5] Selecting 6 signal features...")
    FEATURES = NUM_FEATURES + CAT_FEATURES
    X = train[FEATURES].copy()
    y = train[CFG.TARGET]
    test_X = test[FEATURES].copy()
    print(f"   Numerical features ({len(NUM_FEATURES)}): {NUM_FEATURES}")
    print(f"   Categorical features ({len(CAT_FEATURES)}): {CAT_FEATURES}")
    print(f"   Total features: {len(FEATURES)}")
    print(f"   Dropped {len(train.columns) - len(FEATURES) - 1} noise columns")

    # LabelEncode categoricals for LGBM native categorical handling
    le_crop = LabelEncoder()
    le_mulch = LabelEncoder()
    X['Crop_Growth_Stage'] = le_crop.fit_transform(X['Crop_Growth_Stage'])
    X['Mulching_Used'] = le_mulch.fit_transform(X['Mulching_Used'])
    test_X['Crop_Growth_Stage'] = le_crop.transform(test_X['Crop_Growth_Stage'])
    test_X['Mulching_Used'] = le_mulch.transform(test_X['Mulching_Used'])
    CAT_FEATURE_IDX = [FEATURES.index('Crop_Growth_Stage'), FEATURES.index('Mulching_Used')]
    print(f"   Categorical handling: LGBM native (no TE)")
    print(f"   Cat feature indices: {CAT_FEATURE_IDX}")

    unique, counts = np.unique(y.values, return_counts=True)
    count_dict = dict(zip(unique, counts))
    avg_count = len(y) / len(unique)
    weights_dict = {cls: avg_count / cnt for cls, cnt in count_dict.items()}
    sample_weights = np.array([weights_dict[yy] for yy in y])

    print(f"\n[3/5] Training LightGBM ({CFG.N_FOLDS}-Fold CV)...")
    oof_probs = np.zeros((len(y), CFG.NUM_CLASSES))
    test_probs = np.zeros((len(test_X), CFG.NUM_CLASSES))
    kf = StratifiedKFold(n_splits=CFG.N_FOLDS, shuffle=True, random_state=42)
    fold_scores = []
    t0 = time.time()

    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
        fold_start = time.time()
        print(f"\n   Fold {fold+1}/{CFG.N_FOLDS}: Training...", end=" ", flush=True)

        X_train = X.iloc[train_idx].copy()
        X_val = X.iloc[val_idx].copy()
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        train_weights = sample_weights[train_idx]

        dtrain = lgb.Dataset(X_train, label=y_train, weight=train_weights,
                              categorical_feature=CAT_FEATURE_IDX)
        dval = lgb.Dataset(X_val, label=y_val, reference=dtrain,
                           categorical_feature=CAT_FEATURE_IDX)

        callbacks = [
            lgb.early_stopping(stopping_rounds=150),
            lgb.log_evaluation(period=0),
        ]
        model = lgb.train(
            LGBM_PARAMS,
            dtrain,
            num_boost_round=2000,
            valid_sets=[dval],
            callbacks=callbacks,
        )
        best_iter = model.best_iteration

        val_probs = model.predict(X_val)
        oof_probs[val_idx] = val_probs
        test_probs += model.predict(test_X) / CFG.N_FOLDS

        fold_acc = accuracy_score(y_val.values, val_probs)
        fold_scores.append(fold_acc)

        del model, dtrain, dval
        gc.collect()

        elapsed = (time.time() - t0) / 60
        print(f"BA: {fold_acc:.5f} | Iter: {best_iter} | Time: {time.time()-fold_start:.0f}s | Total: {elapsed:.1f}min")

    oof_cv = accuracy_score(y.values, oof_probs)
    print(f"\n   Raw OOF BA: {oof_cv:.5f}")

    print(f"\n[4/5] Optimizing class weights...")
    optimal_weights = optimize_class_weights(oof_probs, y.values, n_trials=200)
    weights = np.array(optimal_weights)
    oof_probs_opt = oof_probs * weights
    test_probs_opt = test_probs * weights
    opt_cv = accuracy_score(y.values, np.argmax(oof_probs_opt, axis=1))
    print(f"   Optimized OOF BA: {opt_cv:.5f}")

    print(f"\n[5/5] Saving outputs...")
    np.save(f"oof_probs_{CFG.VERSION_NAME}.npy", oof_probs_opt)
    np.save(f"test_probs_{CFG.VERSION_NAME}.npy", test_probs_opt)
    print(f"   [SAVED] test_probs_{CFG.VERSION_NAME}.npy (shape: {test_probs_opt.shape})")
    print(f"   [SAVED] oof_probs_{CFG.VERSION_NAME}.npy")
    sub_df = pd.DataFrame({
        'id': test_id,
        CFG.TARGET: [idx2target[p] for p in np.argmax(test_probs_opt, axis=1)]
    })
    sub_df.to_csv(f"sub_{CFG.VERSION_NAME}.csv", index=False)
    print(f"   [SAVED] sub_{CFG.VERSION_NAME}.csv")

    print(f"\n{'='*80}")
    print(f"V30 RESULTS — LightGBM Signal-Only 6 Raw Features ({CFG.DEVICE})")
    print(f"{'='*80}")
    print(f"Raw OOF BA: {oof_cv:.5f}")
    print(f"Optimized OOF BA: {opt_cv:.5f}")
    print(f"Weights: [{optimal_weights[0]:.4f}, {optimal_weights[1]:.4f}, {optimal_weights[2]:.4f}]")
    print(f"Fold scores: {[f'{s:.5f}' for s in fold_scores]}")
    print(f"\nTotal time: {(time.time() - t0_all) / 60:.1f} min")
    print("="*80)
