"""
S6E4 V28 - CatBoost on Optimized Threshold Formula Features (GPU)
================================================================================
Diversity Tier: Tier 1 — Formula Features × Different Algorithm
Lock Broken: Feature Lock (9 features vs ~340) + Threshold Lock (optimized vs Deotte)

Model: CatBoostClassifier with built-in categorical handling
Data:  4 threshold features (optimized for competition data) + 2 raw categoricals
       NO Target Encoding, NO digit features, NO frequency encoding, NO noise features

Reference:
- Chris Deotte: https://www.kaggle.com/competitions/playground-series-s6e4/discussion/687460
  -> Original data generated by formula using 6 features. Deotte thresholds: 25, 30, 300, 10
- kashifalikhan360 (comment #3441770): Fine-tuned thresholds on competition data:
  -> soil < 24.995 (Deotte: 25) — roughly same
  -> temp > 29.249 (Deotte: 30) — roughly same
  -> rain < 730.66 (Deotte: 300) — DRASTICALLY DIFFERENT (2.4x)
  -> wind > 9.843 (Deotte: 10) — roughly same
  -> LR on these features: ~0.94 BA, XGB on 3 logit features: ~0.9745 BA

Key difference from V26: rain threshold 730.66 vs 300.
Samples with Rainfall 300-730 get DIFFERENT binary values. This creates diversity
BETWEEN formula models while fitting competition data better.

Features:
  4 threshold binaries (optimized cut-points):
    1. soil_lt_24_995  = Soil_Moisture < 24.995
    2. temp_gt_29_249  = Temperature_C > 29.249
    3. rain_lt_730_66  = Rainfall_mm < 730.66
    4. wind_gt_9_843   = Wind_Speed_kmh > 9.843
  2 raw categoricals (CatBoost handles internally):
    5. Crop_Growth_Stage (Flowering/Harvest/Sowing/Vegetative)
    6. Mulching_Used (Yes/No)

Expected: BA ~0.965-0.978 | Disagreement from V1 ~10-15% | From V26 ~5-10%
Est. Time: ~15 min (9 features, CatBoost GPU = fastest)

Pipeline: Load data -> Create 4 threshold binaries + 2 raw cats -> CatBoost GPU ->
          BA early stopping -> Raw OOF -> Class weight optimization -> Final

No ensembling, no blending, no multi-seed (Rule 6).
"""

import warnings
import gc
import time
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from catboost import CatBoostClassifier, Pool

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 100)

class CFG:
    VERSION_NAME = "v28"
    EXP_ID = "S6E4_V28_CB_Optimized_Threshold_Formula"
    DEVICE = "GPU"
    TRAIN_PATH = "/kaggle/input/datasets/blamerx/oof-and-submission/S6E4/Dataset/train.csv"
    TEST_PATH = "/kaggle/input/datasets/blamerx/oof-and-submission/S6E4/Dataset/test.csv"
    TARGET = 'Irrigation_Need'
    NUM_CLASSES = 3
    N_FOLDS = 10
    RANDOM_SEED = 2026

# kashifalikhan360's optimized thresholds (fine-tuned on competition data)
THRESHOLDS = {
    'soil': 24.995027697723284,
    'temp': 29.248587059272676,
    'rain': 730.6597547287315,
    'wind': 9.843173785375448,
}

CB_PARAMS = {
    'iterations': 2000,
    'learning_rate': 0.05,
    'depth': 6,
    'loss_function': 'MultiClass',
    'random_seed': CFG.RANDOM_SEED,
    'task_type': 'GPU',
    'verbose': 0,
    'class_weights': None,  # handled via sample weights
}

def accuracy_score(y_true, y_pred):
    if len(y_pred.shape) == 2:
        y_pred = np.argmax(y_pred, axis=1)
    C = 3
    acc = 0.0
    for i in range(C):
        acc += np.sum((y_true == i) & (y_pred == i)) / np.sum(y_true == i) / C
    return acc

def create_optimized_threshold_features(df):
    """Create 4 threshold binaries (optimized for competition data) + keep 2 raw categoricals."""
    df = df.copy()
    df['soil_lt_24_995'] = (df['Soil_Moisture'] < THRESHOLDS['soil']).astype(np.int8)
    df['temp_gt_29_249'] = (df['Temperature_C'] > THRESHOLDS['temp']).astype(np.int8)
    df['rain_lt_730_66'] = (df['Rainfall_mm'] < THRESHOLDS['rain']).astype(np.int8)
    df['wind_gt_9_843'] = (df['Wind_Speed_kmh'] > THRESHOLDS['wind']).astype(np.int8)
    return df

def optimize_class_weights(oof_probs, y_true, n_trials=200):
    best_score = accuracy_score(y_true, oof_probs)
    best_weights = [1.0, 1.0, 1.0]
    for trial in range(n_trials):
        cw1 = np.random.uniform(0.5, 3.0)
        cw2 = np.random.uniform(0.5, 3.0)
        cw3 = np.random.uniform(0.5, 3.0)
        weights = np.array([cw1, cw2, cw3])
        adjusted_probs = oof_probs * weights
        preds = np.argmax(adjusted_probs, axis=1)
        score = accuracy_score(y_true, preds)
        if score > best_score:
            best_score = score
            best_weights = [cw1, cw2, cw3]
    print(f"   Optimized BA: {best_score:.5f}")
    print(f"   Best Weights: [{best_weights[0]:.4f}, {best_weights[1]:.4f}, {best_weights[2]:.4f}]")
    return best_weights

if __name__ == "__main__":
    t0_all = time.time()
    print("="*80)
    print(f"Starting {CFG.EXP_ID}")
    print(f"Device: {CFG.DEVICE}")
    print(f"Folds: {CFG.N_FOLDS}")
    print("="*80)

    print("\n[1/5] Loading data...")
    train = pd.read_csv(CFG.TRAIN_PATH)
    test = pd.read_csv(CFG.TEST_PATH)
    train = train.drop(columns=['id'])
    test_id = pd.read_csv(CFG.TEST_PATH)['id']
    test = test.drop(columns=['id'])
    print(f"   Train shape: {train.shape}")
    print(f"   Test shape: {test.shape}")

    target2idx = {'Low': 0, 'Medium': 1, 'High': 2}
    idx2target = {0: 'Low', 1: 'Medium', 2: 'High'}
    train[CFG.TARGET] = train[CFG.TARGET].map(target2idx)

    print("\n   Class Distribution:")
    class_counts = train[CFG.TARGET].value_counts().sort_index()
    for cls, count in class_counts.items():
        print(f"     Class {cls}: {count:,} ({100*count/len(train):.1f}%)")

    print("\n[2/5] Creating optimized threshold features...")
    train = create_optimized_threshold_features(train)
    test = create_optimized_threshold_features(test)
    FEATURES = [
        'soil_lt_24_995', 'temp_gt_29_249', 'rain_lt_730_66', 'wind_gt_9_843',
        'Crop_Growth_Stage', 'Mulching_Used',
    ]
    CAT_FEATURES = ['Crop_Growth_Stage', 'Mulching_Used']
    cat_idx = [FEATURES.index(c) for c in CAT_FEATURES]
    print(f"   Features ({len(FEATURES)}): {FEATURES}")
    print(f"   Categorical features (indices): {cat_idx}")
    print(f"   Thresholds (optimized): soil<{THRESHOLDS['soil']:.3f}, temp>{THRESHOLDS['temp']:.3f}, rain<{THRESHOLDS['rain']:.3f}, wind>{THRESHOLDS['wind']:.3f}")

    unique, counts = np.unique(train[CFG.TARGET].values, return_counts=True)
    count_dict = dict(zip(unique, counts))
    avg_count = len(train) / len(unique)
    weights_dict = {cls: avg_count / cnt for cls, cnt in count_dict.items()}
    sample_weights = np.array([weights_dict[y] for y in train[CFG.TARGET]])

    print(f"\n[3/5] Training CatBoost ({CFG.N_FOLDS}-Fold CV)...")
    X = train[FEATURES].copy()
    y = train[CFG.TARGET]
    test_X = test[FEATURES].copy()
    oof_probs = np.zeros((len(y), CFG.NUM_CLASSES))
    test_probs = np.zeros((len(test_X), CFG.NUM_CLASSES))
    kf = StratifiedKFold(n_splits=CFG.N_FOLDS, shuffle=True, random_state=42)
    fold_scores = []
    t0 = time.time()

    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
        fold_start = time.time()
        print(f"\n   Fold {fold+1}/{CFG.N_FOLDS}: Training...", end=" ", flush=True)

        X_train = X.iloc[train_idx].copy()
        X_val = X.iloc[val_idx].copy()
        X_test_fold = test_X.copy()
        y_tr = y.iloc[train_idx]
        y_val = y.iloc[val_idx]
        train_w = sample_weights[train_idx]

        train_pool = Pool(X_train, y_tr, cat_features=cat_idx, weight=train_w)
        val_pool = Pool(X_val, y_val, cat_features=cat_idx)
        test_pool = Pool(X_test_fold, cat_features=cat_idx)

        model = CatBoostClassifier(
            **CB_PARAMS,
            early_stopping_rounds=150,
            eval_metric='Accuracy',
        )
        model.fit(train_pool, eval_set=val_pool, verbose=False)

        best_iter = model.best_iteration_ + 1
        val_probs = model.predict_proba(val_pool)
        oof_probs[val_idx] = val_probs
        test_probs += model.predict_proba(test_pool) / CFG.N_FOLDS

        fold_acc = accuracy_score(y_val.values, val_probs)
        fold_scores.append(fold_acc)

        del model, train_pool, val_pool, test_pool
        gc.collect()

        elapsed = (time.time() - t0) / 60
        print(f"BA: {fold_acc:.5f} | Iter: {best_iter} | Time: {time.time()-fold_start:.0f}s | Total: {elapsed:.1f}min")

    oof_cv = accuracy_score(y.values, oof_probs)
    print(f"\n   Raw OOF BA: {oof_cv:.5f}")

    print(f"\n[4/5] Optimizing class weights...")
    optimal_weights = optimize_class_weights(oof_probs, y.values, n_trials=200)
    weights = np.array(optimal_weights)
    oof_probs_opt = oof_probs * weights
    test_probs_opt = test_probs * weights
    opt_cv = accuracy_score(y.values, np.argmax(oof_probs_opt, axis=1))
    print(f"   Optimized OOF BA: {opt_cv:.5f}")

    print(f"\n[5/5] Saving outputs...")
    np.save(f"oof_probs_{CFG.VERSION_NAME}.npy", oof_probs_opt)
    np.save(f"test_probs_{CFG.VERSION_NAME}.npy", test_probs_opt)
    print(f"   [SAVED] test_probs_{CFG.VERSION_NAME}.npy (shape: {test_probs_opt.shape})")
    print(f"   [SAVED] oof_probs_{CFG.VERSION_NAME}.npy")
    sub_df = pd.DataFrame({
        'id': test_id,
        CFG.TARGET: [idx2target[p] for p in np.argmax(test_probs_opt, axis=1)]
    })
    sub_df.to_csv(f"sub_{CFG.VERSION_NAME}.csv", index=False)
    print(f"   [SAVED] sub_{CFG.VERSION_NAME}.csv")

    print(f"\n{'='*80}")
    print(f"V28 RESULTS — CatBoost Optimized Threshold Formula ({CFG.DEVICE})")
    print(f"{'='*80}")
    print(f"Raw OOF BA: {oof_cv:.5f}")
    print(f"Optimized OOF BA: {opt_cv:.5f}")
    print(f"Weights: [{optimal_weights[0]:.4f}, {optimal_weights[1]:.4f}, {optimal_weights[2]:.4f}]")
    print(f"Fold scores: {[f'{s:.5f}' for s in fold_scores]}")
    print(f"\nTotal time: {(time.time() - t0_all) / 60:.1f} min")
    print("="*80)
